# File: azure-pipelines.yml
trigger:
- main

#trigger: none
#pr:
# branches:
#  include:
#  - '*' # must quote since '*' is a YAML reserved character; we want a string

resources:
  repositories:
    - repository: MvcConsoleGood
      type: github
      name: saurabs/MvcConsoleGood
      ref: refs/heads/main
      endpoint: saurabs


extends:
  template: simple-param.yml
  parameters:
      yesNo: false # set to a non-boolean value to have the build fail
